apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 31080
    targetPort: 3000
    protocol: TCP
  selector:
   app: api